config/routes.rb
Rails.application.routes.draw do
  resources :links

  get '/l/:slug', to: 'links#chqto_link', as: :chqto_link

  post '/chtqo_private_link/:id', to: 'links#chtqo_private_link', as: 'chtqo_private_link'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  get '*unmatched_route', to: 'pages#not_found'

end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  has_many :statistics, dependent: :destroy
  before_save :generate_slug

  validates :link_type, :url, presence: true
  validates :expiration, presence: true, if: :temporary?
  validate :date_not_before_today, if: :temporary?
  validates :password, presence: true, if: :private?
  validates :name, format: { with: /\A[A-Za-z\s]+\z/, message: "only allows letters and spaces" }, allow_blank: true
  validates :url, format: { with: URI::DEFAULT_PARSER.make_regexp }

  before_save :unset_password_or_expiration
  enum link_type: {
    public_link: 0,
    private_link: 1,
    ephemeral_link: 2,
    temporary_link: 3
  }

  def expired?
    expiration < DateTime.current
  end

  def days_since_creation
    (Date.today - created_at.to_date).to_i
  end

  private

  def generate_slug
    return if slug.present?

    unique_slug = SecureRandom.hex(6)
    unique_slug = SecureRandom.hex(6) while Link.exists?(slug: unique_slug)
    self.slug = unique_slug
  end

  def public?
    link_type == 'temporary_link'
  end

  def private?
    link_type == 'private_link'
  end

  def ephemeral?
    link_type == 'private_link'
  end

  def temporary?
    link_type == 'temporary_link'
  end

  def date_not_before_today
    errors.add(:expiration, "can't be before today's date") if expiration.present? && expiration < DateTime.now
  end

  def unset_password_or_expiration
    self.expiration = nil unless temporary?
    self.password = nil unless private?
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[show edit update destroy chtqo_private_link]
  before_action :authenticate_user!, except: %i[chqto_link chtqo_private_link]
  def index
    @pagy, @links = pagy(Link.all.where(user_id: current_user).order(created_at: :desc))
  end

  def show
    stats = @link.statistics.order(created_at: :desc)
    @pagy, @statistics = if filter_params.present?
      pagy(StatisticFilter.new(stats, filter_params).filter)
    else
      pagy(stats)
    end

    @clicks = {
      total: stats.count,
      since_creation: (@link.days_since_creation.zero? ? stats.count.to_f : (stats.count / @link.days_since_creation).to_f)
    }
    @clicks[:total_between_dates] = @statistics.count if filter_params[:start_date].present? && filter_params[:end_date].present?

    flash[:warning] = 'Link is not Active anymore' if @link.ephemeral_link? && !@link.active
    flash[:warning] = 'Link Expired' if @link.temporary_link? && @link.expired?
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to links_path, success: 'Link was created'
    else
      flash[:warning] = @link.errors.full_messages.join(', ')
      redirect_to new_link_path
    end
  end

  def edit; end

  def update
    if @link.update(link_params)
      redirect_to links_url, success: 'Link was updated'
    else
      flash[:warning] = @link.errors.full_messages.join(', ')
      redirect_to edit_link_path
    end
  end

  def destroy
    @link.destroy
    redirect_to links_url, notice: 'Link was deleted'
  end

  def chqto_link
    @link = Link.find_by(slug: params[:slug])
    if @link.present?
      link_type_action
    else
      @error = '404 - Not Found'
      render 'errors/error_page', status: :not_found
    end
  end

  def chtqo_private_link
    if @link.nil? || @link.password != params[:password]
      flash[:warning] = 'Invalid password'
      redirect_to chqto_link_url(slug: @link.slug)
    else
      create_link_stats
      redirect_to @link.url, allow_other_host: true
    end
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:link_type, :name, :expiration, :url, :password).merge(user_id: current_user.id)
  end

  def filter_params
    params.fetch(:link, {}).permit(:ip, :start_date, :end_date)
  end

  def link_type_action
    case @link.link_type
    when 'public_link'
      create_link_stats
      redirect_to @link.url, allow_other_host: true
    when 'ephemeral_link'
      handle_public_or_ephemeral_link
    when 'private_link'
      render :chqto_link
    when 'temporary_link'
      handle_temporary_link
    end
  end

  def handle_public_or_ephemeral_link
    if @link.active
      @link.update(active: false)
      create_link_stats
      redirect_to @link.url, allow_other_host: true
    else
      @error = '403 - Forbidden'
      render 'errors/error_page', status: :forbidden
    end
  end

  def handle_temporary_link
    if @link.expired?
      @link.update(active: false)
      @error = '404 - Not Found'
      render 'errors/error_page', status: :not_found
    else
      create_link_stats
      redirect_to @link.url, allow_other_host: true
    end
  end

  def create_link_stats
    Statistic.create(link: @link, ip: request.remote_ip, clicked_date: Time.now)
  end
end

app/helpers/link_helper.rb
module LinkHelper
  def get_url(slug)
    url_for(controller: 'links', action: 'chqto_link', slug: slug, only_path: false)
  end

  def link_name(name)
    name.present? ? name : 'Link'
  end
end

app/views/links/_link.html.erb
<tr class="table-row">
  <td class="table-data" data-label="Name"><%= link.name%></td>
  <td class="table-data" data-label="Go to Link"><%= button_to link_name(link.name), chqto_link_path(link.slug), method: :get, data: {turbo: false}, class:'button'%></td>
  <td class="table-data" data-label="Link"><%= get_url(link.slug)%></td>
  <td class="table-data" data-label="Type"><%= link.link_type%></td>
   <td class="table-data" data-label="Active"><%= link.active%></td>
  <td class="table-data" data-label="See Stats">
    <%= link_to 'See',link_path(link) %>
  </td>
  <td class="table-data" data-label="Edit"><%= link_to 'Edit link', edit_link_path(link) %></td>
  <td class="table-data" data-label="Delete">
    <%= button_to 'Delete Link',link_path(link), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" },method: :delete, class:'button' %>
  </td>
</tr>

app/views/links/chqto_link.html.erb
<div class="form-container">
  <%= form_with(data: {turbo: false}, url: chtqo_private_link_path(@link), method: :post) do |form| %>
  <div class="form-card form-card-small">
    <%= form.text_field :password, class:"card-form-input",
    placeholder: "Contraseña" %>

    <%= form.submit 'Aceptar', class:"card-form-button" %>
  </div>
  <% end %>
</div>

app/views/links/edit.html.erb
<div class="form-container">
<%= form_with(model: @link, method: :patch,data: {turbo: false}) do |form| %>
  <div class="form-card form-card-large" data-controller="link-type-inputs">
  <h1 class="card-form-title ">Edit Link</h1>

    <%= form.text_field :name, class:"card-form-input",
    placeholder: "Name" %>

    <%= form.text_field :url, class:"card-form-input",
    placeholder: "Url" %>

    <%= form.label :link_type, class:"text-form" %>
    <%= form.select :link_type, Link.link_types.keys.map { |type| [type.humanize, type] },
    {}, class: "card-form-input", data: {action: 'change->link-type-inputs#onChange'} %>

    <%= form.text_field :password, class:"card-form-input display-none",
    placeholder: "Password", data: { link_type_inputs_target: 'password_input' } %>

    <%= form.label :expiration, class:"text-form display-none", data: {link_type_inputs_target: 'date_label'} %>
    <%= form.date_field :expiration, class: "card-form-input display-none", data: {link_type_inputs_target: 'date_input'} %>

    <%= form.submit 'Update Link', class:"card-form-button card-form-button-margincard-form-button-margin" %>

  </div>
<% end %>
</div>

app/views/links/index.html.erb
<div class="container">
<div class="new-link-position">
  <h1>Your Links</h1>
  <div>
    <%= button_to 'New Link', new_link_path, method: :get, class:"button" %>
  </div>
</div>

<table class="table-class">
  <thead class="table-thead">
    <th class="table-head">Name</th>
    <th class="table-head">Go to Link</th>
    <th class="table-head">Link</th>
    <th class="table-head">Type</th>
    <th class="table-head">Active</th>
    <th class="table-head">See Stats</th>
    <th class="table-head">Edit</th>
    <th class="table-head">Delete</th>
  </thead>
  <tbody class="table-body">
    <%= render partial: "link", collection: @links %>
  </tbody>
</table>

<%== pagy_nav(@pagy) %>

</div>

app/views/links/new.html.erb
<div class="form-container">
  <%= form_with(model: @link,data: {turbo: false}) do |form| %>
    <div class="form-card form-card-large" data-controller="link-type-inputs">
      <h1 class="card-form-title ">New Link</h1>

      <%= form.text_field :name, class:"card-form-input",
      placeholder: "Name" %>

      <%= form.text_field :url, class:"card-form-input",
      placeholder: "Url" %>


      <%= form.label :link_type, class:"text-form" %>
      <%= form.select :link_type, Link.link_types.keys.map { |type| [type.humanize, type] },
      {}, class: "card-form-input", data: {action: 'change->link-type-inputs#onChange'}%>

      <%= form.text_field :password, class:"card-form-input display-none",
      placeholder: "Password", data: { link_type_inputs_target: 'password_input' } %>

      
      <%= form.label :expiration, class:"text-form display-none", data: {link_type_inputs_target: 'date_label'} %>
      <%= form.date_field :expiration, class: "card-form-input display-none", data: {link_type_inputs_target: 'date_input'} %>


      <%= form.submit 'Create Link', class:"card-form-button card-form-button-margin" %>

    </div>
  <% end %>
</div>

app/views/links/show.html.erb
<%= render partial: "statistics/table_statistics", locals: { link: @link, statistics: @statistics } %>